### ISSUE TITLE
Getting Error: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by Evacch** [gr2m/iterate-cron-action#4]
I am still encountering an error, even after hardcoding the token and cron values.

In main.yaml,
```
            - name: Set cron schedule
              uses: gr2m/set-cron-schedule-action@v2
              with:
                token: "abc123"
                cron: "*/1 * * * *"
```

After triggering the workflow, getting the following error:
```
Run gr2m/set-cron-schedule-action@v2
  with:
    token: ***
    cron: */1 * * * *
  env:
    pythonLocation: /home/runner/_work/_tool/Python/3.10.15/x64
    PKG_CONFIG_PATH: /home/runner/_work/_tool/Python/3.10.15/x64/lib/pkgconfig
    Python_ROOT_DIR: /home/runner/_work/_tool/Python/3.10.15/x64
    Python[2](https://github.com/xxxxx/actions/runs/12289694654/job/34295637022#step:8:2)_ROOT_DIR: /home/runner/_work/_tool/Python/[3](https://github.com/xxxxx/actions/runs/12289694654/job/34295637022#step:8:3).10.15/x64
    Python3_ROOT_DIR: /home/runner/_work/_tool/Python/3.10.15/x6[4](https://github.com/xxxxx/actions/runs/12289694654/job/34295637022#step:8:4)
    LD_LIBRARY_PATH: /home/runner/_work/_tool/Python/3.10.1[5](https://github.com/xxxxx/actions/runs/12289694654/job/34295637022#step:8:5)/x64/lib
    cron_expression: */1 * * * *
TypeError: Cannot read properties of undefined (reading 'map')
    at main (/home/runner/_work/_actions/gr2m/set-cron-schedule-action/v2/dist/index.js:140:51)
Error: Cannot read properties of undefined (reading 'map')
```
